
#ifndef DARIADBNET_SERVER_EXPORTS_H
#define DARIADBNET_SERVER_EXPORTS_H

#ifdef SHARED_EXPORTS_BUILT_AS_STATIC
#  define DARIADBNET_SERVER_EXPORTS
#  define LIBNET_SERVER_NO_EXPORT
#else
#  ifndef DARIADBNET_SERVER_EXPORTS
#    ifdef libnet_server_EXPORTS
        /* We are building this library */
#      define DARIADBNET_SERVER_EXPORTS __declspec(dllexport)
#    else
        /* We are using this library */
#      define DARIADBNET_SERVER_EXPORTS __declspec(dllimport)
#    endif
#  endif

#  ifndef LIBNET_SERVER_NO_EXPORT
#    define LIBNET_SERVER_NO_EXPORT 
#  endif
#endif

#ifndef LIBNET_SERVER_DEPRECATED
#  define LIBNET_SERVER_DEPRECATED __declspec(deprecated)
#endif

#ifndef LIBNET_SERVER_DEPRECATED_EXPORT
#  define LIBNET_SERVER_DEPRECATED_EXPORT DARIADBNET_SERVER_EXPORTS LIBNET_SERVER_DEPRECATED
#endif

#ifndef LIBNET_SERVER_DEPRECATED_NO_EXPORT
#  define LIBNET_SERVER_DEPRECATED_NO_EXPORT LIBNET_SERVER_NO_EXPORT LIBNET_SERVER_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define LIBNET_SERVER_NO_DEPRECATED
#endif

#endif
